config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get "restaurants", to: "restaurants#restaurants", as: :restaurants

  # get "restaurants/:id", to: "restaurants#show", as: :restaurant

  # get "new", to: "restaurants#new"

  # post "restaurants", to: "restaurants#create"

  # resources :reviews, only: [:new,:create]

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end



# Prefix Verb   URI Pattern                                       Controller#Action
# restaurant_reviews POST   /restaurants/:restaurant_id/reviews(.:format)     reviews#create
# new_restaurant_review GET    /restaurants/:restaurant_id/reviews/new(.:format) reviews#new
#        restaurants GET    /restaurants(.:format)                            restaurants#index
#                    POST   /restaurants(.:format)                            restaurants#create
#     new_restaurant GET    /restaurants/new(.:format)                        restaurants#new
#    edit_restaurant GET    /restaurants/:id/edit(.:format)                   restaurants#edit
#         restaurant GET    /restaurants/:id(.:format)                        restaurants#show
#                    PATCH  /restaurants/:id(.:format)                        restaurants#update
#                    PUT    /restaurants/:id(.:format)                        restaurants#update
#                    DELETE /restaurants/:id(.:format)                        restaurants#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  LIST = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: LIST }, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true , inclusion: { in: 0..5 } , numericality: { only_integer: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
   @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end


  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

before_action :find_restaurant

  def new
    @review = Review.new
  end

  def create

   @review = Review.new(review_params)
   @review.restaurant = @restaurant
   if @review.save
    redirect_to restaurant_path(@restaurant)
   else
     render :new
   end
  end

private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content,:rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
  <div class="navbar bg-white text-dark mt-2">
  <div class="container">
    <h1>Logo - Resident advisor</h1>
    <h2>Leave us the reviews!</h2>
  </div>
  </div>
  </header>
  <body >
  <div class="container mt-5">
    <%= yield %>
  </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to "#{restaurant.name}" , restaurant_path(restaurant)%></li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Hello Form</h1>

<%  list = ["chinese", "italian", "japanese", "french", "belgian"] %>

<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, collection: list %>
  <%= f.input :phone_number %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.category %></p>
<p><%= @restaurant.phone_number %></p>

<h1>Reviews</h1>


<ul>
<% @restaurant.reviews.each do |restaurant| %>
  <li><%= restaurant.content %></li>
<% end  %>
</ul>

<%= link_to "Go back", restaurants_path%>
<%= link_to "Add Review", new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>